### ISSUE TITLE
Certain Non-ASL, Non-Echolink Nodes have an Off Format

### ISSUE THREAD

**Issue by jxmx** [AllStarLink/Allmon3#109]
```
Apr 23 02:19:16 maxwell asl-statmon[9756]: asl-statmon: ERROR: list index out of range
Apr 23 02:19:16 maxwell asl-statmon[9756]: Traceback (most recent call last):
Apr 23 02:19:16 maxwell asl-statmon[9756]:   File "/usr/bin/asl-statmon", line 554, in <module>
Apr 23 02:19:16 maxwell asl-statmon[9756]:     raise e
Apr 23 02:19:16 maxwell asl-statmon[9756]:   File "/usr/bin/asl-statmon", line 490, in <module>
Apr 23 02:19:16 maxwell asl-statmon[9756]:     parse_xstat(c_node, xstat)
Apr 23 02:19:16 maxwell asl-statmon[9756]:   File "/usr/bin/asl-statmon", line 225, in parse_xstat
Apr 23 02:19:16 maxwell asl-statmon[9756]:     "CSTATE" : ce[6] , "PTT" : False, "SSK" : -1, "SSU" : -1, "MODE" : "Local Monitor" } )
Apr 23 02:19:16 maxwell asl-statmon[9756]: IndexError: list index out of range
```

**Comment by jxmx** [comment]
From old asl-statmon
