### ISSUE TITLE
Bad File Descriptor Execption in ami_conn

### ISSUE THREAD

**Issue by jxmx** [AllStarLink/Allmon3#135]
```
Jun  6 22:11:41 Allmon allmon3[32681]: ERROR: (asl_allmon.ami_conn) asl_cmd_response() socket.timeout
Jun  6 22:11:41 Allmon allmon3[32681]: ERROR: (asl_allmon.ami_parser) asl_cmd() exception <class 'socket.timeout'>
Jun  6 22:11:41 Allmon allmon3[32681]: ERROR: (asl_allmon.ami_parser) asl_cmd() message <class 'socket.timeout'>
Jun  6 22:11:41 Allmon allmon3[32681]: ERROR: (asl_allmon.allmon3_ws_status) received socket.timeout; trying to reconnect
Jun  6 22:12:02 Allmon allmon3[32681]: ERROR: (asl_allmon.ami_conn) connection failed to 162.218.153.251:5036: timed out
Jun  6 22:12:02 Allmon allmon3[32681]: INFO: (asl_allmon.allmon3_ws_status) connection reestablished after 1 retries
Jun  6 22:12:02 Allmon allmon3[32681]: ERROR: (asl_allmon.ami_conn) asl_cmd_response() Exception: <class 'OSError'>
Jun  6 22:12:02 Allmon allmon3[32681]: ERROR: (asl_allmon.ami_conn) asl_cmd_response() Message: [Errno 9] Bad file descriptor
Jun  6 22:12:02 Allmon allmon3[32681]: ERROR: (asl_allmon.ami_parser) asl_cmd() exception <class 'OSError'>
Jun  6 22:12:02 Allmon allmon3[32681]: ERROR: (asl_allmon.ami_parser) asl_cmd() message <class 'OSError'>
Jun  6 22:12:02 Allmon allmon3[32681]: ERROR: (asl_allmon.allmon3_ws_status) [Errno 9] Bad file descriptor
Jun  6 22:12:07 Allmon allmon3[32681]: ERROR: (asl_allmon.ami_conn) asl_cmd_response() socket.timeout
Jun  6 22:12:07 Allmon allmon3[32681]: ERROR: (asl_allmon.ami_parser) asl_cmd() exception <class 'socket.timeout'>
Jun  6 22:12:07 Allmon allmon3[32681]: ERROR: (asl_allmon.ami_parser) asl_cmd() message <class 'socket.timeout'>
Jun  6 22:12:07 Allmon allmon3[32681]: ERROR: (asl_allmon.allmon3_ws_voter) received socket.timeout; trying to reconnect
Jun  6 22:12:07 Allmon allmon3[32681]: INFO: (asl_allmon.allmon3_ws_status) server closing
Jun  6 22:12:07 Allmon allmon3[32681]: INFO: (asl_allmon.allmon3_ws_status) server closed
Jun  6 22:12:07 Allmon allmon3[32681]: INFO: (asl_allmon.allmon3_ws_status) connection closed
Jun  6 22:12:07 Allmon allmon3[32681]: INFO: (asl_allmon.allmon3_ws_status) connection closed
Jun  6 22:12:07 Allmon allmon3[32681]: INFO: (asl_allmon.allmon3_ws_status) connection closed
Jun  6 22:12:07 Allmon allmon3[32681]: Traceback (most recent call last):
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/bin/allmon3", line 230, in <module>
Jun  6 22:12:07 Allmon allmon3[32681]:     asyncio.run(start_tasks())
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
Jun  6 22:12:07 Allmon allmon3[32681]:     return loop.run_until_complete(main)
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
Jun  6 22:12:07 Allmon allmon3[32681]:     return future.result()
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/bin/allmon3", line 116, in start_tasks
Jun  6 22:12:07 Allmon allmon3[32681]:     raise e
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/bin/allmon3", line 106, in start_tasks
Jun  6 22:12:07 Allmon allmon3[32681]:     await asyncio.gather(*tasks)
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/asl_allmon/allmon3_ws_status/__init__.py", line 151, in main
Jun  6 22:12:07 Allmon allmon3[32681]:     await self.broadcast()
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/asl_allmon/allmon3_ws_status/__init__.py", line 98, in broadcast
Jun  6 22:12:07 Allmon allmon3[32681]:     raise e
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/asl_allmon/allmon3_ws_status/__init__.py", line 84, in broadcast
Jun  6 22:12:07 Allmon allmon3[32681]:     parser.asl_cmd("core show version")
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/asl_allmon/ami_parser/__init__.py", line 70, in asl_cmd
Jun  6 22:12:07 Allmon allmon3[32681]:     raise e
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/asl_allmon/ami_parser/__init__.py", line 36, in asl_cmd
Jun  6 22:12:07 Allmon allmon3[32681]:     c_response = self.__ami_conn.asl_cmd_response(cmd)
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/asl_allmon/ami_conn/__init__.py", line 123, in asl_cmd_response
Jun  6 22:12:07 Allmon allmon3[32681]:     raise e
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/asl_allmon/ami_conn/__init__.py", line 89, in asl_cmd_response
Jun  6 22:12:07 Allmon allmon3[32681]:     self.socket.settimeout(5)
Jun  6 22:12:07 Allmon allmon3[32681]: OSError: [Errno 9] Bad file descriptor
Jun  6 22:12:07 Allmon allmon3[32681]: Future exception was never retrieved
Jun  6 22:12:07 Allmon allmon3[32681]: future: <Future finished exception=ConnectionClosedError(None, None, None)>
Jun  6 22:12:07 Allmon allmon3[32681]: Traceback (most recent call last):
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/bin/allmon3", line 230, in <module>
Jun  6 22:12:07 Allmon allmon3[32681]:     asyncio.run(start_tasks())
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
Jun  6 22:12:07 Allmon allmon3[32681]:     return loop.run_until_complete(main)
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
Jun  6 22:12:07 Allmon allmon3[32681]:     return future.result()
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/bin/allmon3", line 116, in start_tasks
Jun  6 22:12:07 Allmon allmon3[32681]:     raise e
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/bin/allmon3", line 106, in start_tasks
Jun  6 22:12:07 Allmon allmon3[32681]:     await asyncio.gather(*tasks)
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/asl_allmon/allmon3_ws_status/__init__.py", line 151, in main
Jun  6 22:12:07 Allmon allmon3[32681]:     await self.broadcast()
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/asl_allmon/allmon3_ws_status/__init__.py", line 98, in broadcast
Jun  6 22:12:07 Allmon allmon3[32681]:     raise e
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/asl_allmon/allmon3_ws_status/__init__.py", line 84, in broadcast
Jun  6 22:12:07 Allmon allmon3[32681]:     parser.asl_cmd("core show version")
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/asl_allmon/ami_parser/__init__.py", line 70, in asl_cmd
Jun  6 22:12:07 Allmon allmon3[32681]:     raise e
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/asl_allmon/ami_parser/__init__.py", line 36, in asl_cmd
Jun  6 22:12:07 Allmon allmon3[32681]:     c_response = self.__ami_conn.asl_cmd_response(cmd)
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/asl_allmon/ami_conn/__init__.py", line 123, in asl_cmd_response
Jun  6 22:12:07 Allmon allmon3[32681]:     raise e
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/asl_allmon/ami_conn/__init__.py", line 89, in asl_cmd_response
Jun  6 22:12:07 Allmon allmon3[32681]:     self.socket.settimeout(5)
Jun  6 22:12:07 Allmon allmon3[32681]: OSError: [Errno 9] Bad file descriptor
Jun  6 22:12:07 Allmon allmon3[32681]: During handling of the above exception, another exception occurred:
Jun  6 22:12:07 Allmon allmon3[32681]: Traceback (most recent call last):
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 968, in transfer_data
Jun  6 22:12:07 Allmon allmon3[32681]:     message = await self.read_message()
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 1038, in read_message
Jun  6 22:12:07 Allmon allmon3[32681]:     frame = await self.read_data_frame(max_size=self.max_size)
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 1113, in read_data_frame
Jun  6 22:12:07 Allmon allmon3[32681]:     frame = await self.read_frame(max_size)
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 1170, in read_frame
Jun  6 22:12:07 Allmon allmon3[32681]:     frame = await Frame.read(
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/websockets/legacy/framing.py", line 69, in read
Jun  6 22:12:07 Allmon allmon3[32681]:     data = await reader(2)
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3.9/asyncio/streams.py", line 723, in readexactly
Jun  6 22:12:07 Allmon allmon3[32681]:     await self._wait_for_data('readexactly')
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3.9/asyncio/streams.py", line 517, in _wait_for_data
Jun  6 22:12:07 Allmon allmon3[32681]:     await self._waiter
Jun  6 22:12:07 Allmon allmon3[32681]: asyncio.exceptions.CancelledError
Jun  6 22:12:07 Allmon allmon3[32681]: The above exception was the direct cause of the following exception:
Jun  6 22:12:07 Allmon allmon3[32681]: websockets.exceptions.ConnectionClosedError: no close frame received or sent
Jun  6 22:12:07 Allmon allmon3[32681]: Future exception was never retrieved
Jun  6 22:12:07 Allmon allmon3[32681]: future: <Future finished exception=ConnectionClosedError(None, None, None)>
Jun  6 22:12:07 Allmon allmon3[32681]: Traceback (most recent call last):
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/bin/allmon3", line 230, in <module>
Jun  6 22:12:07 Allmon allmon3[32681]:     asyncio.run(start_tasks())
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
Jun  6 22:12:07 Allmon allmon3[32681]:     return loop.run_until_complete(main)
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
Jun  6 22:12:07 Allmon allmon3[32681]:     return future.result()
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/bin/allmon3", line 116, in start_tasks
Jun  6 22:12:07 Allmon allmon3[32681]:     raise e
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/bin/allmon3", line 106, in start_tasks
Jun  6 22:12:07 Allmon allmon3[32681]:     await asyncio.gather(*tasks)
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/asl_allmon/allmon3_ws_status/__init__.py", line 151, in main
Jun  6 22:12:07 Allmon allmon3[32681]:     await self.broadcast()
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/asl_allmon/allmon3_ws_status/__init__.py", line 98, in broadcast
Jun  6 22:12:07 Allmon allmon3[32681]:     raise e
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/asl_allmon/allmon3_ws_status/__init__.py", line 84, in broadcast
Jun  6 22:12:07 Allmon allmon3[32681]:     parser.asl_cmd("core show version")
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/asl_allmon/ami_parser/__init__.py", line 70, in asl_cmd
Jun  6 22:12:07 Allmon allmon3[32681]:     raise e
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/asl_allmon/ami_parser/__init__.py", line 36, in asl_cmd
Jun  6 22:12:07 Allmon allmon3[32681]:     c_response = self.__ami_conn.asl_cmd_response(cmd)
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/asl_allmon/ami_conn/__init__.py", line 123, in asl_cmd_response
Jun  6 22:12:07 Allmon allmon3[32681]:     raise e
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/asl_allmon/ami_conn/__init__.py", line 89, in asl_cmd_response
Jun  6 22:12:07 Allmon allmon3[32681]:     self.socket.settimeout(5)
Jun  6 22:12:07 Allmon allmon3[32681]: OSError: [Errno 9] Bad file descriptor
Jun  6 22:12:07 Allmon allmon3[32681]: During handling of the above exception, another exception occurred:
Jun  6 22:12:07 Allmon allmon3[32681]: Traceback (most recent call last):
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 968, in transfer_data
Jun  6 22:12:07 Allmon allmon3[32681]:     message = await self.read_message()
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 1038, in read_message
Jun  6 22:12:07 Allmon allmon3[32681]:     frame = await self.read_data_frame(max_size=self.max_size)
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 1113, in read_data_frame
Jun  6 22:12:07 Allmon allmon3[32681]:     frame = await self.read_frame(max_size)
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 1170, in read_frame
Jun  6 22:12:07 Allmon allmon3[32681]:     frame = await Frame.read(
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/websockets/legacy/framing.py", line 69, in read
Jun  6 22:12:07 Allmon allmon3[32681]:     data = await reader(2)
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3.9/asyncio/streams.py", line 723, in readexactly
Jun  6 22:12:07 Allmon allmon3[32681]:     await self._wait_for_data('readexactly')
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3.9/asyncio/streams.py", line 517, in _wait_for_data
Jun  6 22:12:07 Allmon allmon3[32681]:     await self._waiter
Jun  6 22:12:07 Allmon allmon3[32681]: asyncio.exceptions.CancelledError
Jun  6 22:12:07 Allmon allmon3[32681]: The above exception was the direct cause of the following exception:
Jun  6 22:12:07 Allmon allmon3[32681]: websockets.exceptions.ConnectionClosedError: no close frame received or sent
Jun  6 22:12:07 Allmon allmon3[32681]: Future exception was never retrieved
Jun  6 22:12:07 Allmon allmon3[32681]: future: <Future finished exception=ConnectionClosedError(None, None, None)>
Jun  6 22:12:07 Allmon allmon3[32681]: Traceback (most recent call last):
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/bin/allmon3", line 230, in <module>
Jun  6 22:12:07 Allmon allmon3[32681]:     asyncio.run(start_tasks())
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
Jun  6 22:12:07 Allmon allmon3[32681]:     return loop.run_until_complete(main)
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
Jun  6 22:12:07 Allmon allmon3[32681]:     return future.result()
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/bin/allmon3", line 116, in start_tasks
Jun  6 22:12:07 Allmon allmon3[32681]:     raise e
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/bin/allmon3", line 106, in start_tasks
Jun  6 22:12:07 Allmon allmon3[32681]:     await asyncio.gather(*tasks)
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/asl_allmon/allmon3_ws_status/__init__.py", line 151, in main
Jun  6 22:12:07 Allmon allmon3[32681]:     await self.broadcast()
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/asl_allmon/allmon3_ws_status/__init__.py", line 98, in broadcast
Jun  6 22:12:07 Allmon allmon3[32681]:     raise e
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/asl_allmon/allmon3_ws_status/__init__.py", line 84, in broadcast
Jun  6 22:12:07 Allmon allmon3[32681]:     parser.asl_cmd("core show version")
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/asl_allmon/ami_parser/__init__.py", line 70, in asl_cmd
Jun  6 22:12:07 Allmon allmon3[32681]:     raise e
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/asl_allmon/ami_parser/__init__.py", line 36, in asl_cmd
Jun  6 22:12:07 Allmon allmon3[32681]:     c_response = self.__ami_conn.asl_cmd_response(cmd)
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/asl_allmon/ami_conn/__init__.py", line 123, in asl_cmd_response
Jun  6 22:12:07 Allmon allmon3[32681]:     raise e
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/asl_allmon/ami_conn/__init__.py", line 89, in asl_cmd_response
Jun  6 22:12:07 Allmon allmon3[32681]:     self.socket.settimeout(5)
Jun  6 22:12:07 Allmon allmon3[32681]: OSError: [Errno 9] Bad file descriptor
Jun  6 22:12:07 Allmon allmon3[32681]: During handling of the above exception, another exception occurred:
Jun  6 22:12:07 Allmon allmon3[32681]: Traceback (most recent call last):
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 968, in transfer_data
Jun  6 22:12:07 Allmon allmon3[32681]:     message = await self.read_message()
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 1038, in read_message
Jun  6 22:12:07 Allmon allmon3[32681]:     frame = await self.read_data_frame(max_size=self.max_size)
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 1113, in read_data_frame
Jun  6 22:12:07 Allmon allmon3[32681]:     frame = await self.read_frame(max_size)
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/websockets/legacy/protocol.py", line 1170, in read_frame
Jun  6 22:12:07 Allmon allmon3[32681]:     frame = await Frame.read(
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3/dist-packages/websockets/legacy/framing.py", line 69, in read
Jun  6 22:12:07 Allmon allmon3[32681]:     data = await reader(2)
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3.9/asyncio/streams.py", line 723, in readexactly
Jun  6 22:12:07 Allmon allmon3[32681]:     await self._wait_for_data('readexactly')
Jun  6 22:12:07 Allmon allmon3[32681]:   File "/usr/lib/python3.9/asyncio/streams.py", line 517, in _wait_for_data
Jun  6 22:12:07 Allmon allmon3[32681]:     await self._waiter
Jun  6 22:12:07 Allmon allmon3[32681]: asyncio.exceptions.CancelledError
Jun  6 22:12:07 Allmon allmon3[32681]: The above exception was the direct cause of the following exception:
Jun  6 22:12:07 Allmon allmon3[32681]: websockets.exceptions.ConnectionClosedError: no close frame received or sent
```

**Comment by jxmx** [comment]
Fixed even more in 4f989c5..a2d621b
