### ISSUE TITLE
Service needs restart after loss of internet

### ISSUE THREAD

**Issue by Pross** [AllStarLink/Allmon3#187]
**Describe the bug**
Im not sure if this is a me thing or an actual thing, noticed this a couple of times now.
If the allstar3 looses connection to the internet it seems to crash the allstar3 systemd process and needs to be restarted 
with `sudo systemctl restart allmon3`.
Im not sure why it should need to be connected to the internet anyway as my nodes are all on my local network.

**Comment by jxmx** [comment]
Please provide logging out of `/var/log/syslog` or `journalctl -b -u allmon3.service`. What version of allmon3 are you using? There was a bug fixed in v1.0.1 that would have caused crashing during an extended network outage when the ASL database couldn't be downloaded.

**Comment by Pross** [comment]
Im using latest 1.0.2 version this part of the log includes the crash and me restarting the service.

```
Dec 06 13:10:26 allmon3 allmon3[31354]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 06 13:10:33 allmon3 allmon3[31354]: INFO: (asl_allmon.node_db) Updated node database in 6.89 seconds
Dec 06 13:25:33 allmon3 allmon3[31354]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 06 13:25:36 allmon3 allmon3[31354]: INFO: (asl_allmon.node_db) Updated node database in 3.02 seconds
Dec 06 13:40:36 allmon3 allmon3[31354]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 06 13:40:48 allmon3 allmon3[31354]: INFO: (asl_allmon.node_db) Updated node database in 12.16 seconds
Dec 06 13:55:48 allmon3 allmon3[31354]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 06 13:55:57 allmon3 allmon3[31354]: INFO: (asl_allmon.node_db) Updated node database in 8.86 seconds
Dec 06 14:10:57 allmon3 allmon3[31354]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 06 14:11:09 allmon3 allmon3[31354]: INFO: (asl_allmon.node_db) Updated node database in 11.89 seconds
Dec 06 14:26:09 allmon3 allmon3[31354]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 06 14:26:11 allmon3 allmon3[31354]: INFO: (asl_allmon.node_db) Updated node database in 2.11 seconds
Dec 06 14:37:25 allmon3 allmon3[31354]: INFO: (asl_allmon.allmon3_ws_status) connection open
Dec 06 14:37:25 allmon3 allmon3[31354]: INFO: (asl_allmon.allmon3_ws_status) connection open
Dec 06 14:39:49 allmon3 allmon3[31354]: INFO: (asl_allmon.allmon3_ws_status) connection closed
Dec 06 14:39:50 allmon3 allmon3[31354]: INFO: (asl_allmon.allmon3_ws_status) connection open
Dec 06 14:39:50 allmon3 allmon3[31354]: INFO: (asl_allmon.allmon3_ws_status) connection open
Dec 06 14:39:50 allmon3 allmon3[31354]: INFO: (asl_allmon.allmon3_ws_status) connection closed
Dec 06 14:41:11 allmon3 allmon3[31354]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 06 14:41:31 allmon3 allmon3[31354]: ERROR: (asl_allmon.node_db) Failed to retrieve database with error: <urlopen error [Errno -3] Temporary failure in name resolution>
Dec 06 14:41:31 allmon3 allmon3[31354]: ERROR: (asl_allmon.node_db) Waiting 5 minutes to try again: attempt 1/5
Dec 06 14:46:31 allmon3 allmon3[31354]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 06 14:46:52 allmon3 allmon3[31354]: ERROR: (asl_allmon.node_db) Failed to retrieve database with error: <urlopen error [Errno -3] Temporary failure in name resolution>
Dec 06 14:46:52 allmon3 allmon3[31354]: ERROR: (asl_allmon.node_db) Waiting 5 minutes to try again: attempt 2/5
Dec 06 14:51:52 allmon3 allmon3[31354]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 06 14:51:54 allmon3 allmon3[31354]: INFO: (asl_allmon.node_db) Updated node database in 2.13 seconds
Dec 06 14:51:54 allmon3 allmon3[31354]: WARNING: (asl_allmon.ami_conn) asl_cmd_response() BrokenPipeError
Dec 06 14:51:54 allmon3 allmon3[31354]: WARNING: (asl_allmon.allmon3_ws_status) ami_conn socket problem for node 585831: socket broken pipe
Dec 06 14:51:54 allmon3 allmon3[31354]: INFO: (asl_allmon.allmon3_ws_status) node: 585831 - sleeping for RETRY_INTERVAL of 15
Dec 06 14:51:54 allmon3 allmon3[31354]: INFO: (asl_allmon.allmon3_ws_status) connection closed
Dec 06 14:51:54 allmon3 allmon3[31354]: INFO: (asl_allmon.allmon3_ws_status) connection closed
Dec 06 14:52:09 allmon3 allmon3[31354]: INFO: (asl_allmon.allmon3_ws_status) node: 585831 - attempting reconnection retry #1
Dec 06 14:52:09 allmon3 allmon3[31354]: INFO: (asl_allmon.allmon3_ws_status) node: 585831 - connection reestablished after 1 retries
Dec 06 15:06:54 allmon3 allmon3[31354]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 06 15:06:58 allmon3 allmon3[31354]: INFO: (asl_allmon.node_db) Updated node database in 4.26 seconds
Dec 06 15:21:58 allmon3 allmon3[31354]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 06 15:22:18 allmon3 allmon3[31354]: ERROR: (asl_allmon.node_db) Failed to retrieve database with error: <urlopen error [Errno -3] Temporary failure in name resolution>
Dec 06 15:22:18 allmon3 allmon3[31354]: ERROR: (asl_allmon.node_db) Waiting 5 minutes to try again: attempt 1/5
Dec 06 15:27:18 allmon3 allmon3[31354]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 06 15:27:23 allmon3 allmon3[31354]: INFO: (asl_allmon.node_db) Updated node database in 4.36 seconds
Dec 06 15:42:23 allmon3 allmon3[31354]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 06 15:42:43 allmon3 allmon3[31354]: ERROR: (asl_allmon.node_db) Failed to retrieve database with error: <urlopen error [Errno -3] Temporary failure in name resolution>
Dec 06 15:42:43 allmon3 allmon3[31354]: ERROR: (asl_allmon.node_db) Waiting 5 minutes to try again: attempt 1/5
Dec 06 15:47:43 allmon3 allmon3[31354]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 06 15:48:03 allmon3 allmon3[31354]: ERROR: (asl_allmon.node_db) Failed to retrieve database with error: <urlopen error [Errno -3] Temporary failure in name resolution>
Dec 06 15:48:03 allmon3 allmon3[31354]: ERROR: (asl_allmon.node_db) Waiting 5 minutes to try again: attempt 2/5
Dec 06 15:53:03 allmon3 allmon3[31354]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 06 15:53:23 allmon3 allmon3[31354]: ERROR: (asl_allmon.node_db) Failed to retrieve database with error: <urlopen error [Errno -3] Temporary failure in name resolution>
Dec 06 15:53:23 allmon3 allmon3[31354]: ERROR: (asl_allmon.node_db) Waiting 5 minutes to try again: attempt 3/5
Dec 06 15:58:23 allmon3 allmon3[31354]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 06 15:58:43 allmon3 allmon3[31354]: ERROR: (asl_allmon.node_db) Failed to retrieve database with error: <urlopen error [Errno -3] Temporary failure in name resolution>
Dec 06 15:58:43 allmon3 allmon3[31354]: ERROR: (asl_allmon.node_db) Waiting 5 minutes to try again: attempt 4/5
Dec 06 16:03:43 allmon3 allmon3[31354]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 06 16:04:03 allmon3 allmon3[31354]: ERROR: (asl_allmon.node_db) Failed to retrieve database with error: <urlopen error [Errno -3] Temporary failure in name resolution>
Dec 06 16:04:03 allmon3 allmon3[31354]: ERROR: (asl_allmon.node_db) Waiting 5 minutes to try again: attempt 5/5
Dec 06 16:09:03 allmon3 allmon3[31354]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 06 16:09:24 allmon3 allmon3[31354]: ERROR: (asl_allmon.node_db) Failed to retrieve database with error: <urlopen error [Errno -3] Temporary failure in name resolution>
Dec 06 16:09:24 allmon3 allmon3[31354]: ERROR: (asl_allmon.node_db) Waiting 5 minutes to try again: attempt 6/5
Dec 06 16:14:24 allmon3 allmon3[31354]: INFO: (asl_allmon.allmon3_ws_status) server closing
Dec 06 16:14:24 allmon3 allmon3[31354]: INFO: (asl_allmon.allmon3_ws_status) server closing
Dec 06 16:14:24 allmon3 allmon3[31354]: Traceback (most recent call last):
Dec 06 16:14:24 allmon3 allmon3[31354]:   File "/usr/bin/allmon3", line 247, in <module>
Dec 06 16:14:24 allmon3 allmon3[31354]:     asyncio.run(start_tasks())
Dec 06 16:14:24 allmon3 allmon3[31354]:   File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
Dec 06 16:14:24 allmon3 allmon3[31354]:     return runner.run(main)
Dec 06 16:14:24 allmon3 allmon3[31354]:            ^^^^^^^^^^^^^^^^
Dec 06 16:14:24 allmon3 allmon3[31354]:   File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
Dec 06 16:14:24 allmon3 allmon3[31354]:     return self._loop.run_until_complete(task)
Dec 06 16:14:24 allmon3 allmon3[31354]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 06 16:14:24 allmon3 allmon3[31354]:   File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
Dec 06 16:14:24 allmon3 allmon3[31354]:     return future.result()
Dec 06 16:14:24 allmon3 allmon3[31354]:            ^^^^^^^^^^^^^^^
Dec 06 16:14:24 allmon3 allmon3[31354]:   File "/usr/bin/allmon3", line 127, in start_tasks
Dec 06 16:14:24 allmon3 allmon3[31354]:     raise e
Dec 06 16:14:24 allmon3 allmon3[31354]:   File "/usr/bin/allmon3", line 114, in start_tasks
Dec 06 16:14:24 allmon3 allmon3[31354]:     await asyncio.gather(*tasks)
Dec 06 16:14:24 allmon3 allmon3[31354]:   File "/usr/lib/python3/dist-packages/asl_allmon/node_db/__init__.py", line 82, in db_updater
Dec 06 16:14:24 allmon3 allmon3[31354]:     self.get_allmon_db()
Dec 06 16:14:24 allmon3 allmon3[31354]:   File "/usr/lib/python3/dist-packages/asl_allmon/node_db/__init__.py", line 45, in get_allmon_db
Dec 06 16:14:24 allmon3 allmon3[31354]:     nodedb = re.split(r"\n", dbf)
Dec 06 16:14:24 allmon3 allmon3[31354]:                       ^^^^^
Dec 06 16:14:24 allmon3 allmon3[31354]: UnboundLocalError: cannot access local variable 'dbf' where it is not associated with a value
Dec 06 16:14:24 allmon3 systemd[1]: allmon3.service: Main process exited, code=exited, status=1/FAILURE
Dec 06 16:14:24 allmon3 systemd[1]: allmon3.service: Failed with result 'exit-code'.
Dec 06 16:14:24 allmon3 systemd[1]: allmon3.service: Consumed 31.848s CPU time.
Dec 06 17:48:09 allmon3 systemd[1]: Starting allmon3.service - Allmon3 daemon...
Dec 06 17:48:09 allmon3 systemd[1]: Started allmon3.service - Allmon3 daemon.
Dec 06 17:48:10 allmon3 allmon3[31764]: INFO: (asl_allmon.web_configs) Allmon3 Master HTTP port is 16080
Dec 06 17:48:10 allmon3 allmon3[31764]: INFO: (asl_allmon.web_configs) Allmon3 websockets starting port is 16700
Dec 06 17:48:10 allmon3 allmon3[31764]: INFO: (asl_allmon.web_configs) Binding sevices to all addresses
Dec 06 17:48:10 allmon3 allmon3[31764]: INFO: (allmon3) no %s found; no menu data available
Dec 06 17:48:10 allmon3 allmon3[31764]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 06 17:48:12 allmon3 allmon3[31764]: INFO: (asl_allmon.node_db) Updated node database in 1.94 seconds
Dec 06 17:48:12 allmon3 allmon3[31764]: INFO: (allmon3) starting status ws 585830@192.168.1.142 on port 16700
Dec 06 17:48:12 allmon3 allmon3[31764]: INFO: (allmon3) starting cmd ws 585830@192.168.1.142 on port 16701
Dec 06 17:48:12 allmon3 allmon3[31764]: INFO: (allmon3) starting status ws 585831@192.168.1.190 on port 16702
Dec 06 17:48:12 allmon3 allmon3[31764]: INFO: (allmon3) starting cmd ws 585831@192.168.1.190 on port 16703
Dec 06 17:48:12 allmon3 allmon3[31764]: INFO: (allmon3) starting allmon3 master ws on port 16080
Dec 06 17:48:12 allmon3 allmon3[31764]: INFO: (allmon3) starting node_db updater
Dec 06 17:48:12 allmon3 allmon3[31764]: INFO: (asl_allmon.allmon3_ws_cmd) server listening on [::]:16701
Dec 06 17:48:12 allmon3 allmon3[31764]: INFO: (asl_allmon.allmon3_ws_cmd) server listening on 0.0.0.0:16701
Dec 06 17:48:12 allmon3 allmon3[31764]: INFO: (asl_allmon.allmon3_ws_cmd) server listening on [::]:16703
Dec 06 17:48:12 allmon3 allmon3[31764]: INFO: (asl_allmon.allmon3_ws_cmd) server listening on 0.0.0.0:16703
Dec 06 17:48:12 allmon3 allmon3[31764]: INFO: (asl_allmon.allmon3_ws_status) server listening on 0.0.0.0:16702
Dec 06 17:48:12 allmon3 allmon3[31764]: INFO: (asl_allmon.allmon3_ws_status) server listening on [::]:16702
Dec 06 17:48:12 allmon3 allmon3[31764]: INFO: (asl_allmon.allmon3_ws_status) broadcasting status for 585831 on port 16702
Dec 06 17:48:12 allmon3 allmon3[31764]: INFO: (asl_allmon.allmon3_ws_status) server listening on 0.0.0.0:16700
Dec 06 17:48:12 allmon3 allmon3[31764]: INFO: (asl_allmon.allmon3_ws_status) server listening on [::]:16700
Dec 06 17:48:12 allmon3 allmon3[31764]: INFO: (asl_allmon.allmon3_ws_status) broadcasting status for 585830 on port 16700
Dec 06 17:48:14 allmon3 allmon3[31764]: INFO: (asl_allmon.allmon3_ws_status) connection open
Dec 06 17:48:14 allmon3 allmon3[31764]: INFO: (asl_allmon.allmon3_ws_status) connection open
Dec 06 18:03:12 allmon3 allmon3[31764]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 06 18:03:14 allmon3 allmon3[31764]: INFO: (asl_allmon.node_db) Updated node database in 2.04 seconds
Dec 06 18:18:14 allmon3 allmon3[31764]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 06 18:18:15 allmon3 allmon3[31764]: INFO: (asl_allmon.node_db) Updated node database in 1.65 seconds
Dec 06 18:33:15 allmon3 allmon3[31764]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 06 18:33:17 allmon3 allmon3[31764]: INFO: (asl_allmon.node_db) Updated node database in 2.01 seconds
Dec 06 18:48:17 allmon3 allmon3[31764]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 06 18:48:19 allmon3 allmon3[31764]: INFO: (asl_allmon.node_db) Updated node database in 1.92 seconds
Dec 06 19:03:19 allmon3 allmon3[31764]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 06 19:03:21 allmon3 allmon3[31764]: INFO: (asl_allmon.node_db) Updated node database in 1.70 seconds
Dec 06 19:18:21 allmon3 allmon3[31764]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 06 19:18:23 allmon3 allmon3[31764]: INFO: (asl_allmon.node_db) Updated node database in 1.87 seconds
Dec 06 19:33:23 allmon3 allmon3[31764]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 06 19:33:25 allmon3 allmon3[31764]: INFO: (asl_allmon.node_db) Updated node database in 2.02 seconds
Dec 06 19:48:25 allmon3 allmon3[31764]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
Dec 06 19:48:28 allmon3 allmon3[31764]: INFO: (asl_allmon.node_db) Updated node database in 3.60 seconds
```

**Comment by jxmx** [comment]
Yeah, looks like another network bug in the node database code....

**Comment by jxmx** [comment]
Please try copying `src/asl_allmon/node_db/__init__.py` to `/usr/lib/python3/dist-packages/asl_allmon/node_db` and give that a try to see if it fixes that crash?

**Comment by Pross** [comment]
It gives up on the 6th try now without a crash
```
2023-12-07T13:41:07.504520+00:00 allmon3 allmon3[33538]: ERROR: (asl_allmon.node_db) Waiting 5 minutes to try again: attempt 5/5
2023-12-07T13:46:07.513247+00:00 allmon3 allmon3[33538]: INFO: (asl_allmon.node_db) Retrieving database from https://allmondb.allstarlink.org/
2023-12-07T13:46:07.672375+00:00 allmon3 allmon3[33538]: ERROR: (asl_allmon.node_db) Failed to retrieve database with error: <urlopen error [Errno -3] Temporary failure in name resolution>
2023-12-07T13:46:07.672891+00:00 allmon3 allmon3[33538]: ERROR: (asl_allmon.node_db) Waiting 5 minutes to try again: attempt 6/5
2023-12-07T13:51:07.680636+00:00 allmon3 allmon3[33538]: ERROR: (asl_allmon.node_db) Error processing nodedb after retrival: cannot access local variable 'dbf' where it is not associated with a value
2023-12-07T13:51:07.710557+00:00 allmon3 allmon3[33538]: INFO: (asl_allmon.allmon3_ws_status) connection closed
2023-12-07T13:51:08.092748+00:00 allmon3 allmon3[33538]: INFO: (asl_allmon.allmon3_ws_status) connection open
2023-12-07T13:51:08.259912+00:00 allmon3 allmon3[33538]: INFO: (asl_allmon.allmon3_ws_status) connection open
2023-12-07T13:51:08.615300+00:00 allmon3 allmon3[33538]: INFO: (asl_allmon.allmon3_ws_status) connection closed
```

**Comment by jxmx** [comment]
Okay, at least that solves the crash. I need to rewrite that whole module per #185.

**Comment by Pross** [comment]
Yea I was going to mention the dash was totally locked up for the whole time it was retrying Thx for the fix!
