### ISSUE TITLE
asl-statmon: Check response before passing to parseSawStat/XStat

### ISSUE THREAD

**Issue by jxmx** [AllStarLink/Allmon3#22]
```
ar  6 04:40:11 maxwell asl-statmon[1371]: asl-statmon: ERROR: timed out
Mar  6 04:40:11 maxwell asl-statmon[1371]: asl-statmon: ERROR: expected string or bytes-like object
Mar  6 04:40:11 maxwell asl-statmon[1371]: Traceback (most recent call last):
Mar  6 04:40:11 maxwell asl-statmon[1371]:   File "/usr/local/bin/asl-statmon", line 494, in <module>
Mar  6 04:40:11 maxwell asl-statmon[1371]:     raise e
Mar  6 04:40:11 maxwell asl-statmon[1371]:   File "/usr/local/bin/asl-statmon", line 439, in <module>
Mar  6 04:40:11 maxwell asl-statmon[1371]:     parseSawStat(curr_node, sawstat)
Mar  6 04:40:11 maxwell asl-statmon[1371]:   File "/usr/local/bin/asl-statmon", line 159, in parseSawStat
Mar  6 04:40:11 maxwell asl-statmon[1371]:     ra = re.split(r'[\n\r]+', response)
Mar  6 04:40:11 maxwell asl-statmon[1371]:   File "/usr/lib/python3.7/re.py", line 213, in split
Mar  6 04:40:11 maxwell asl-statmon[1371]:     return _compile(pattern, flags).split(string, maxsplit)
Mar  6 04:40:11 maxwell asl-statmon[1371]: TypeError: expected string or bytes-like object
Mar  6 04:40:11 maxwell systemd[1]: asl-statmon@47987.service: Main process exited, code=exited, status=1/FAILURE
Mar  6 04:40:11 maxwell systemd[1]: asl-statmon@47987.service: Failed with result 'exit-code'.
```

**Comment by jxmx** [comment]
This appaers to have been a downstream issue of #33
