### ISSUE TITLE
asl-statmon: Convert node_conns to string-based associative array

### ISSUE THREAD

**Issue by jxmx** [AllStarLink/Allmon3#23]
```
Mar  6 02:51:12 maxwell asl-statmon[1351]: asl-statmon: ERROR: invalid literal for int() with base 10: 'KC8FQV-P'
Mar  6 02:51:12 maxwell asl-statmon[1351]: Traceback (most recent call last):
Mar  6 02:51:12 maxwell asl-statmon[1351]:   File "/usr/local/bin/asl-statmon", line 494, in <module>
Mar  6 02:51:12 maxwell asl-statmon[1351]:     raise e
Mar  6 02:51:12 maxwell asl-statmon[1351]:   File "/usr/local/bin/asl-statmon", line 437, in <module>
Mar  6 02:51:12 maxwell asl-statmon[1351]:     parseXStat(curr_node, xstat)
Mar  6 02:51:12 maxwell asl-statmon[1351]:   File "/usr/local/bin/asl-statmon", line 200, in parseXStat
Mar  6 02:51:12 maxwell asl-statmon[1351]:     if int(ce[1]) in node_database:
Mar  6 02:51:12 maxwell asl-statmon[1351]: ValueError: invalid literal for int() with base 10: 'KC8FQV-P'
Mar  6 02:51:12 maxwell systemd[1]: asl-statmon@48496.service: Main process exited, code=exited, status=1/FAILURE
Mar  6 02:51:12 maxwell systemd[1]: asl-statmon@48496.service: Failed with result 'exit-code'.
```

**Comment by jxmx** [comment]
See #24
