### ISSUE TITLE
asl-statmon: parseXStat encounters a mysterious out-of-range index error

### ISSUE THREAD

**Issue by jxmx** [AllStarLink/Allmon3#24]
```
Mar  6 00:29:28 maxwell asl-statmon[1366]: asl-statmon: ERROR: list index out of range
Mar  6 00:29:28 maxwell asl-statmon[1366]: Traceback (most recent call last):
Mar  6 00:29:28 maxwell asl-statmon[1366]:   File "/usr/local/bin/asl-statmon", line 494, in <module>
Mar  6 00:29:28 maxwell asl-statmon[1366]:     raise e
Mar  6 00:29:28 maxwell asl-statmon[1366]:   File "/usr/local/bin/asl-statmon", line 437, in <module>
Mar  6 00:29:28 maxwell asl-statmon[1366]:     parseXStat(curr_node, xstat)
Mar  6 00:29:28 maxwell asl-statmon[1366]:   File "/usr/local/bin/asl-statmon", line 199, in parseXStat
Mar  6 00:29:28 maxwell asl-statmon[1366]:     "CSTATE" : ce[6] , "PTT" : False, "SSK" : -1, "SSU" : -1, "MODE" : "Initializing" } )
Mar  6 00:29:28 maxwell asl-statmon[1366]: IndexError: list index out of range
```

**Comment by jxmx** [comment]
https://github.com/AllStarLink/Allmon3/commit/fb492a19fd580567571e809a25d4ade857e411c4

**Comment by jxmx** [comment]
https://github.com/AllStarLink/Allmon3/commit/561a82ebc817f710c4bc2f6dd0d25b832016be17

**Comment by jxmx** [comment]
Need to account for the different format of the Echolink and Telephone Portal connections
