### ISSUE TITLE
Not all AMI Instances are "1.0"

### ISSUE THREAD

**Issue by tsawyer** [AllStarLink/Allmon3#3]
Connecting to the AMI isn't working with `asl-statmon asl-statmon.ini`.

```
./asl-statmon 2509 ./asl-statmon.ini
asl-statmon: INFO: No pollinterval= attribute specified, using default 1
asl-statmon: INFO: No retryinterval= attribute specified, using default 15s
asl-statmon: INFO: No retrycount= attribute specified, using default of infinite retries
asl-statmon: ERROR: Connection to 127.0.0.1:5038 is not an Asterisk Call Manager/1.0
```

**asl-statmon.ini**
```
#
# This is just an example for the base .ini elements necessary for
# asl-statmon daemon. In production these values would normally
# be read in from the master-level .ini file
#
# [1999]
# ip = 192.0.2.0     # IP address of the Asterisk (req'd)
# port = 5038        # port of the Asterisk manager (optional, default 5038)
# user = admin       # username of the Asterisk monitor, most commonly 'admin' (req'd)
# pass = password    # password of the monitor user (req'd)
# monport = 6750     # port for the ZMQ listener for this node (req'd)
# pollinterval =     # polling intervial to asterisk (optiona, default = 1)
# retryinterval =    # seconds between retries if initial connection to asterisk is lost (optional, default 15)
# retrycount =       # number of times to retry a lost asterisk connection before ending (optional, default infinite)
#
[2509]
ip=127.0.0.1
user=admin
pass=xxxxxxxx
monport=6750
```

**Comment by jxmx** [comment]
If you telnet to localhost 5038 what do you get? You should see:

```$ telnet localhost 5038
Trying ::1...
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.\
Asterisk Call Manager/1.0
```

**Comment by tsawyer** [comment]
That works. AMI is running.
```
root@NewASL ➜  asl-statmon git:(develop) ✗ telnet 127.0.0.1 5038
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
Asterisk Call Manager
```

localhost works, too.

**Comment by tsawyer** [comment]
I tried dropping the /1.0 off the validation. It didn't work for me, but I know nothing about Python. 

If you'd like a logon to the server, send your public ssh key.

**Comment by jxmx** [comment]
fixed in [71e5d0b](https://github.com/AllStarLink/Allmon3/commit/71e5d0be1eecbae0308ff043ec21d8e6aeb98dfd)

Try now.

**Comment by tsawyer** [comment]
```root@NewASL ➜  asl-statmon git:(develop) ✗ ./asl-statmon 2509 asl-statmon.ini
  File "/usr/src/Allmon3/asl-statmon/./asl-statmon", line 68
    if re.match("^Asterisk Call Manager", part)
                                               ^
SyntaxError: invalid syntax```

**Comment by jxmx** [comment]
Arghhh.... I was editing one file in the new repo and "testing" it in another window in the old location.

**Comment by tsawyer** [comment]
Latest after a pull...
```
./asl-statmon 2509 asl-statmon.ini
asl-statmon: INFO: No pollinterval= attribute specified, using default 1
asl-statmon: INFO: No retryinterval= attribute specified, using default 15s
asl-statmon: INFO: No retrycount= attribute specified, using default of infinite retries
asl-statmon: INFO: Retrieving database from http://allmondb.allstarlink.org/
asl-statmon: INFO: Updated node database in 1.42 seconds
asl-statmon: ERROR: timed out
asl-statmon: ERROR: expected string or bytes-like object
Traceback (most recent call last):
  File "/usr/src/Allmon3/asl-statmon/./asl-statmon", line 476, in <module>
    raise e
  File "/usr/src/Allmon3/asl-statmon/./asl-statmon", line 422, in <module>
    parseSawStat(sawstat)
  File "/usr/src/Allmon3/asl-statmon/./asl-statmon", line 149, in parseSawStat
    ra = re.split(r'[\n\r]+', response)
  File "/usr/lib/python3.9/re.py", line 231, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: expected string or bytes-like object
```

**Comment by tsawyer** [comment]
It runs for a while longer with --debug but eventually errors.
```
asl-statmon: ERROR: timed out
asl-statmon: DEBUG: parseSawStat()
asl-statmon: ERROR: expected string or bytes-like object
asl-statmon: DEBUG: Clean up on aisle 5
Traceback (most recent call last):
  File "/usr/src/Allmon3/asl-statmon/./asl-statmon", line 476, in <module>
    raise e
  File "/usr/src/Allmon3/asl-statmon/./asl-statmon", line 422, in <module>
    parseSawStat(sawstat)
  File "/usr/src/Allmon3/asl-statmon/./asl-statmon", line 149, in parseSawStat
    ra = re.split(r'[\n\r]+', response)
  File "/usr/lib/python3.9/re.py", line 231, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: expected string or bytes-like object
root@NewASL ➜  asl-statmon git:(develop) ✗
```
Don't ya love strongly typed languages?

**Comment by jxmx** [comment]
Try it now.

**Comment by jxmx** [comment]
Certain types of Asterisk installations sends the "end of response" \r\n in a separate response in the TCP flow.

**Comment by jxmx** [comment]
[c1c7fb9](https://github.com/AllStarLink/Allmon3/commit/c1c7fb907474426f54836ee6727ae413b6bdc58d)
