### ISSUE TITLE
Not all socket.timeouts are being handled properly

### ISSUE THREAD

**Issue by jxmx** [AllStarLink/Allmon3#33]
```
Mar  9 14:55:36 maxwell asl-statmon[6241]: asl-statmon: ERROR: ASLCmdResponse() Exception: <class 'socket.timeout'>
Mar  9 14:55:36 maxwell asl-statmon[6241]: asl-statmon: ERROR: ASLCmdResponse() Message: timed out
Mar  9 14:55:36 maxwell asl-statmon[6241]: asl-statmon: ERROR: timed out
Mar  9 14:55:36 maxwell asl-statmon[6241]: Traceback (most recent call last):
Mar  9 14:55:36 maxwell asl-statmon[6241]:   File "/usr/local/bin/asl-statmon", line 522, in <module>
Mar  9 14:55:36 maxwell asl-statmon[6241]:     raise e
Mar  9 14:55:36 maxwell asl-statmon[6241]:   File "/usr/local/bin/asl-statmon", line 464, in <module>
Mar  9 14:55:36 maxwell asl-statmon[6241]:     xstat = ASLCmdResponse(asl, xstat_cmd)
Mar  9 14:55:36 maxwell asl-statmon[6241]:   File "/usr/local/bin/asl-statmon", line 140, in ASLCmdResponse
Mar  9 14:55:36 maxwell asl-statmon[6241]:     raise e
Mar  9 14:55:36 maxwell asl-statmon[6241]:   File "/usr/local/bin/asl-statmon", line 119, in ASLCmdResponse
Mar  9 14:55:36 maxwell asl-statmon[6241]:     part = s.recv(1024)
Mar  9 14:55:36 maxwell asl-statmon[6241]: socket.timeout: timed out
```

**Comment by jxmx** [comment]
https://github.com/AllStarLink/Allmon3/commit/a0100f694152f1dd09a9ba9d4ee9981e4b827f72

**Comment by jxmx** [comment]
Seems to have fixed the issue
