### ISSUE TITLE
Handle ConnectionResetError when AMI force-closes the TCP connection

### ISSUE THREAD

**Issue by tsawyer** [AllStarLink/Allmon3#47]
asl-statmon drops connection to remote node. Seems like this happens when we're debugging something. 

**Screenshots**
```root@ip-172-26-12-227:/usr/src/Allmon3# journalctl -u  asl-statmon@2509.service
-- Logs begin at Wed 2023-03-15 13:24:15 PDT, end at Sun 2023-03-19 14:26:41 PDT. --
Mar 15 13:36:16 ip-172-26-12-227 asl-statmon[11024]: asl-statmon: INFO: Retrieving database from http://allmondb.allstarlink.org/
Mar 15 13:36:17 ip-172-26-12-227 asl-statmon[11024]: asl-statmon: INFO: Updated node database in 0.49 seconds
Mar 15 14:25:24 ip-172-26-12-227 asl-statmon[11024]: asl-statmon: ERROR: asl_cmd_response() BrokenPipeError
Mar 15 14:25:24 ip-172-26-12-227 asl-statmon[11024]: asl-statmon: ERROR: received BrokenPipeError; trying to reconnect
Mar 15 14:25:40 ip-172-26-12-227 asl-statmon[11024]: asl-statmon: INFO: connection reestablished after 1 retries
Mar 15 14:36:18 ip-172-26-12-227 asl-statmon[11024]: asl-statmon: INFO: Retrieving database from http://allmondb.allstarlink.org/
Mar 15 14:36:18 ip-172-26-12-227 asl-statmon[11024]: asl-statmon: INFO: Updated node database in 0.48 seconds
Mar 15 15:36:19 ip-172-26-12-227 asl-statmon[11024]: asl-statmon: INFO: Retrieving database from http://allmondb.allstarlink.org/
Mar 15 15:36:20 ip-172-26-12-227 asl-statmon[11024]: asl-statmon: INFO: Updated node database in 0.49 seconds
Mar 15 16:36:20 ip-172-26-12-227 asl-statmon[11024]: asl-statmon: INFO: Retrieving database from http://allmondb.allstarlink.org/
Mar 15 16:36:20 ip-172-26-12-227 asl-statmon[11024]: asl-statmon: INFO: Updated node database in 0.47 seconds
Mar 15 17:36:21 ip-172-26-12-227 asl-statmon[11024]: asl-statmon: INFO: Retrieving database from http://allmondb.allstarlink.org/
Mar 15 17:36:21 ip-172-26-12-227 asl-statmon[11024]: asl-statmon: INFO: Updated node database in 0.48 seconds
Mar 15 18:36:22 ip-172-26-12-227 asl-statmon[11024]: asl-statmon: INFO: Retrieving database from http://allmondb.allstarlink.org/
Mar 15 18:36:22 ip-172-26-12-227 asl-statmon[11024]: asl-statmon: INFO: Updated node database in 0.49 seconds
Mar 15 19:33:29 ip-172-26-12-227 asl-statmon[11024]: asl-statmon: ERROR: asl_cmd_response() Exception: <class 'ConnectionResetError'>
Mar 15 19:33:29 ip-172-26-12-227 asl-statmon[11024]: asl-statmon: ERROR: asl_cmd_response() Message: [Errno 104] Connection reset by peer
Mar 15 19:33:29 ip-172-26-12-227 asl-statmon[11024]: asl-statmon: ERROR: [Errno 104] Connection reset by peer
Mar 15 19:33:29 ip-172-26-12-227 asl-statmon[11024]: asl-statmon: ERROR: [Errno 32] Broken pipe
Mar 15 19:33:29 ip-172-26-12-227 asl-statmon[11024]: Traceback (most recent call last):
Mar 15 19:33:29 ip-172-26-12-227 asl-statmon[11024]:   File "/usr/local/bin/asl-statmon", line 531, in <module>
Mar 15 19:33:29 ip-172-26-12-227 asl-statmon[11024]:     except Exception as e:
Mar 15 19:33:29 ip-172-26-12-227 asl-statmon[11024]:   File "/usr/local/bin/asl-statmon", line 471, in <module>
Mar 15 19:33:29 ip-172-26-12-227 asl-statmon[11024]:
Mar 15 19:33:29 ip-172-26-12-227 asl-statmon[11024]:   File "/usr/local/bin/asl-statmon", line 144, in asl_cmd_response
Mar 15 19:33:29 ip-172-26-12-227 asl-statmon[11024]:     raise e
Mar 15 19:33:29 ip-172-26-12-227 asl-statmon[11024]:   File "/usr/local/bin/asl-statmon", line 121, in asl_cmd_response
Mar 15 19:33:29 ip-172-26-12-227 asl-statmon[11024]:     part = s.recv(1024)
Mar 15 19:33:29 ip-172-26-12-227 asl-statmon[11024]: ConnectionResetError: [Errno 104] Connection reset by peer
Mar 15 19:33:29 ip-172-26-12-227 systemd[1]: asl-statmon@2509.service: Main process exited, code=exited, status=1/FAILURE
Mar 15 19:33:29 ip-172-26-12-227 systemd[1]: asl-statmon@2509.service: Failed with result 'exit-code'.
```

**Comment by jxmx** [comment]
Looks like Asterisk is forcing the connection closed with a TCP reset. I'll have to handle that error.

**Comment by jxmx** [comment]
e819a9d..69aea78
