### ISSUE TITLE
asl-cmlink: asl_cmd() doesn't handle empty responses properly

### ISSUE THREAD

**Issue by jxmx** [AllStarLink/Allmon3#48]
```
Mar 19 16:55:04 copper asl-cmdlink[1874286]: asl-cmdlink: ERROR: asl_cmd() exception <class 'AttributeError'>
Mar 19 16:55:04 copper asl-cmdlink[1874286]: asl-cmdlink: ERROR: asl_cmd() message <class 'AttributeError'>
Mar 19 16:55:04 copper asl-cmdlink[1874286]: asl-cmdlink: ERROR: 'NoneType' object has no attribute 'group'
Mar 19 16:55:04 copper asl-cmdlink[1874286]: Traceback (most recent call last):
Mar 19 16:55:04 copper asl-cmdlink[1874286]:   File "/usr/local/bin/asl-cmdlink", line 383, in <module>
Mar 19 16:55:04 copper asl-cmdlink[1874286]:     raise e
Mar 19 16:55:04 copper asl-cmdlink[1874286]:   File "/usr/local/bin/asl-cmdlink", line 340, in <module>
Mar 19 16:55:04 copper asl-cmdlink[1874286]:     response = asl_cmd(asl, message)
Mar 19 16:55:04 copper asl-cmdlink[1874286]:   File "/usr/local/bin/asl-cmdlink", line 176, in asl_cmd
Mar 19 16:55:04 copper asl-cmdlink[1874286]:     raise e
Mar 19 16:55:04 copper asl-cmdlink[1874286]:   File "/usr/local/bin/asl-cmdlink", line 148, in asl_cmd
Mar 19 16:55:04 copper asl-cmdlink[1874286]:     return "ERR: {}".format(output.group(1))
Mar 19 16:55:04 copper asl-cmdlink[1874286]: AttributeError: 'NoneType' object has no attribute 'group'
Mar 19 16:55:04 copper systemd[1]: asl-cmdlink@50815.service: Main process exited, code=exited, status=1/FAILURE
Mar 19 16:55:04 copper systemd[1]: asl-cmdlink@50815.service: Failed with result 'exit-code'.
```

**Comment by jxmx** [comment]
https://github.com/AllStarLink/Allmon3/commit/61d12c5141460022b837206abeb028d2596dcc1e
